# Header
menu:
  Home: /
  Archives: /archives
  About: /about

# Logo Image Source
logo_src: /images/logo.svg

# Theme Main Subtitle
subtitle_main: ì‚¬ì§„ì°ëŠ” í”„ë¡œê·¸ë˜ë¨¸ì˜ ì†Œê°œ í˜ì´ì§€ì…ë‹ˆë‹¤.

# Theme Secondary subtitle
susbtitle_secondary: iOS â†’ Server â†’ Androidë¥¼ ê±°ì³ í˜„ì¬ëŠ” Webì„ í•˜ê³ ìˆëŠ” í’€ìŠ¤íƒ(ì´ë¼ì“°ê³  ì¡ë¶€ë¼ ì½ìŠµë‹ˆë‹¤) ê°œë°œìì…ë‹ˆë‹¤ ğŸ˜€

# Footer About Section
about_footer: ê°œë°œê³¼ ê´€ë ¨ëœ ì´ì•¼ê¸°ë¼ë©´ ì–¸ì œë“  ë‚˜ëˆ„ëŠ” ê²ƒì„ ì¢‹ì•„í•©ë‹ˆë‹¤.

# Default post title
default_post_title: ì´ë¦„ì´ ì—†ìŠµë‹ˆë‹¤.

# Default post cover index page (Recommended)
default_cover_index: "http://placehold.it/450x450"

# Default post cover index page (Optional)
default_cover_detail:

# Show Dates for posts and pages
show_dates:

# Comments. Choose one by filling up the information
comments:
  # Disqus comments
  disqus_shortname: portfolio-10
  # Facebook comments
  facebook:
    appid:
    comment_count: 5
    comment_colorscheme: light

# Google Analytics Tracking ID
google_analytics: UA-93952276-1

# Social Accounts
twitter_url: https://twitter.com/developerjin
facebook_url: https://www.facebook.com/kimcheongjin
instagram_url: https://www.instagram.com/developerjin
dribble_url:
github_url: https://github.com/devjin0617
googleplus_url:
behance_url:
fivehundredpx_url:
email_url: me@puding.kr
rss_url:
